version: '3.4'

services:
  newportfolio:
    image: newportfolio
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment: 
      - SECRET_KEY=KEY