version: '3.4'

services:
  newportfolio:
    image: portfolio_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../database/portfolio.db:/app/database/portfolio.db
      - ../database/static/:/app/database/static/